### ISSUE TITLE
Not compatible with aeson-0.10

### ISSUE THREAD

**Issue by rassie** [himura/twitter-types#36]
`aeson` 0.10 has [changed](https://github.com/bos/aeson/issues/287) the semantics of the `.:?` combinator, so `twitter-types` is currently broken for at least the `contributors` field. Using `aeson` 0.9.0.1 seems fine, so `twitter-types` needs either a dependency version upper-bound or an update to use `aeson` 0.10

**Comment by bergmark** [comment]
Bump. The test suite failures looked serious so I've disabled twitter-types and twitter-types-lens on stackage since we have upgraded to aeson-0.10. Please send a pull request to re-enable it when this is fixed. If this happens before new years they will still be included in LTS 4.

Also see the aeson-extra package for compatibility between aeson versions.

**Comment by juhp** [comment]
This can probably be closed now I think.

**Comment by himura** [comment]
Yep, this issue is fixed in #35 and aeson 0.11.
